# config context path to "/" by setting an empty string
server:
  contextPath:

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

jwt:
  header: Authorization
  secret: mySecret
  expiration: 180000
  route:
    authentication:
      path: api/user/login
      refresh: refresh

#logging:
#  level:
#    org.springframework:
#      security: DEBUG